import Head from "next/head";
import NavBar from "./components/NavBar";
import Header from "./components/Header";
import HoldUp from "./components/HoldUp";
import HowWorks from "./components/HowWorks";
import Card from "./components/Card";
import Footer from "./components/Footer";
import Subscribe from "./components/Subscribe";
import GlobalParticipation from "./components/GlobalParticipation";
import Entrepreneurship from "./components/Entrepreneurship";

export default function Home() {
  return (
    <div className="flex flex-col h-screen overflow-x-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex-grow">
        <NavBar />
        <Header />
        <Card />
        <HoldUp />
        <HowWorks />
        <Entrepreneurship />
        <GlobalParticipation />
        <Subscribe />
      </div>
      <Footer />
    </div>
  );
}
